import = [
    # "~/.config/alacritty/themes/alabaster_dark.toml"
    # "~/.config/alacritty/themes/aura.toml"
     "~/.config/alacritty/themes/carbonfox.toml"
    # "~/.config/alacritty/themes/catppuccin_mocha.toml"
    # "~/.config/alacritty/themes/city_lights.toml"
    # "~/.config/alacritty/themes/github_dark_default.toml"
    # "~/.config/alacritty/themes/iris.toml"
    
]

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }

size = 12

[window]
opacity = 0.95
padding = { x = 10, y = 10 }
